services:
  db-service:
    build:
      context: .
      dockerfile: cmd/db-service/Dockerfile
    container_name: db-service
    ports:
      - "${GRPC_PORT}:${GRPC_PORT}"    
    environment:
      - DB_FILE=${DB_FILE}
      - GRPC_PORT
      - REDIS_ADDR
    volumes:
      - db_data:/data
    depends_on:
      - redis

  api-service:
    build:
      context: .
      dockerfile: cmd/api-service/Dockerfile
    container_name: api-service
    ports:
      - "${TODO_PORT}:${TODO_PORT}" 
    environment:
      - DB_SERVICE_ADDRESS=db-service:${GRPC_PORT} 
      - TODO_PORT
    depends_on:
      - db-service
      - redis

  redis:
    image: redis:7-alpine
    container_name: my-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  db_data:
  redis_data: